title: 80 Days
email: contact@80days.in
description: "@fiiv's Travel, work, lifestyle et al"
baseurl: "" # the subpath of your site, e.g. /blog

permalink: /:year-:month-:day/:title

paginate: 10

url: "https://80days.in"
twitter_username: mtimofiiv
github_username:  mtimofiiv

# Build settings
markdown: kramdown

plugins:
  # - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

mike_location: Amed
mike_location_flag: 🇮🇩

feed:
  categories:
    - tech
    - travel
